language: go

go:
  - 1.9.x

go_import_path: github.com/dex4er/collectd-json-influxdb-proxy

install:
  - go get -v github.com/golang/lint/golint
  - go get -v github.com/golang/dep/cmd/dep

script:
  - dep ensure -v
  - go build -v .
  - go vet -x .
  - golint -set_exit_status .
  - go test .
