language: go

go:
  - 1.9.x

install:
  - go get github.com/Masterminds/glide
  - go get github.com/golang/lint/golint

script:
  - glide install
  - GO15VENDOREXPERIMENT=1 go build *.go
  - go vet .
  - golint .
