[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "^16.0.0"

[[constraint]]
  name = "github.com/gin-contrib/expvar"
  branch = "master"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "^1.5.2"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "^1.6.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.2.1"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
